### ISSUE TITLE
ech89

### ISSUE THREAD

**Issue by chi-plus-plus** [mariopepe/KindleAdRemover#1]
Ciao, Scugn1zzo.
L'istruzione "ech89", nello script .sh è un refuso? 
Grazie,
C:

P.S. Grazie per i 10 Euri risparmiati. Se mai passassi da Gaeta, ce li andiamo a bere insieme. :-)

**Comment by mariopepe** [comment]
Ciao! Scusami tantissimo per aver letto solo ora avevo rimosso le notifiche. Sì, era un typo 'ech89' -> 'echo'.
Ho corretto con la commit #2739821 quindi se scarichi ora il codice è corretto.
La versione .app invece non aveva l'errore e aveva sempre funzionato.

Magari! Che bella Gaeta 😍

**Comment by chi-plus-plus** [comment]
A posto: ho scaricato la nuova versione e ha funzionato correttamente.
Ti aspetto per bere :-)
C:

P.S. Che poi, i suggerimenti non sarebbero nemmeno male, se non fossero tutti libri pessimi, tipo Harmony..
