### ISSUE TITLE
Domande sull'utilizzo

### ISSUE THREAD

**Issue by Anshinix** [mariopepe/KindleAdRemover#3]
Ciao @mariopepe 
Mi sono imbattuta in questo bel progetto ma, non essendo pratica, ti faccio qui alcune domande:

1. ho appena acquistato un paperwhite, quindi penso che il dispositivo sia più recente dell'ultimo aggiornamento del software: c'è la possibilità che con il mio non funzioni?
2. facendo questo procedimento si perde la garanzia? (inoltre, nel caso è reversibile? per esempio se si riporta il dispositivo a stato di fabbrica)
3. dopo aver tolto gli ads succede qualcosa se si attiva il wifi sul dispositivo? oppure succede qualcosa quando si accede alla propria area di amazon? (per la serie: sono antisgamo?)
4. il procedimento è quello descritto nel readme semplicemente oppure c'è bisogno di avere conoscenze pregresse? nel senso, ce la posso fare da sola o rischio di rendere il dispositivo inutilizzabile?! :D

Per adesso credo sia tutto, scusami per le domande stupide ma davvero non me ne intendo!
Grazie mille per la pazienza! :)

**Comment by mariopepe** [comment]
Ciao @Anshinix 

Sono contento che ti piaccia!

(questa parte della risposta la ho scritta dopo aver risposto per punti alle domande perché mi sono reso conto che potevo fornire più spiegazioni, magari aggiorno anche il readme in questi giorni)
Comunque, ti spiego in brevissimo cosa fa il codice così appunto vedi che è super sicuro.
Il kindle ha una cartella all'interno della quale salva tutti gli annunci pubblicitari. Come sai, di volta in volta scarica nuova pubblicità da mostrarti. Il mio piccolo tool, altro non fa che rendere quella cartella inutilizzabile. Quindi quando poi il Kindle prova a (write) salvare nuova pubblicità o (read) prendere la pubblicità per mostrartela sullo schermo, non riesce. Dato appunto che la cartella è inutilizzabile (per rendere la cartella inutilizzabile sostituisco la cartella con un file invisibile vuoto).
E quindi niente pubblicità.
Nel momento in cui tu (intenzionalmente o involontariamente, come risultato di un aggiornamento software) cancelli quella cartella che ho reso inutilizzabile, automaticamente il kindle ne genera una nuova e torna la pubblicità.
Tutto il codice viene eseguito solo nella parte accessibile all'utente della memoria di archiviazione del kindle. Quindi se anche cancellassi tutte le cartelle, o ne aggiungessi 100.000 per errore, teoricamente non puoi mai fare un danno permanente al kindle o intaccare la garanzia (al massimo cancelli i tuoi libri, ma questo statement va verificato, non tocco il file system del kindle da parecchio).
Detto questo il codice è fornito as is e senza garanzia, come sempre qualsiasi cosa può andare storta (tipo meteorite 😂).
(E comunque sempre occhio a quali file cancelli dalla memoria, ad esempio spesso ci possono essere dei file relativamente grandi che non sembrano essere importanti, ed eliminarli può sembrare un buon metodo per salvare spazio, ma in realtà sono una sorta di indicizzazione dei PDF che leggi e eliminandoli costringi il kindle a rigenerarli, e se hai moooolti pdf, consumi tanta batteria e ti ritrovi i file cancellati 😊)

(risposta iniziale)
1. Avevo provato di recente con un kindle moderno e secondo me dovrebbe funzionare!
2. Non perdi assolutamente garanzia perché non si sblocca il bootloader. Ed è reversibile, basta ripristinare come hai detto, o anche aggiornando il dispositivo (purtroppo) torna come prima. (ma anche su questo non posso fornirti garanzia)
3. Nono assolutamente non succede nulla. (anche qui, dalla mia esperienza e di altri utenti non succede nulla, ma non posso fornirti garanzia)
4. Nono assolutamente con il solo readme vai tranquilla!

Ciao, Mario! 👋🏻

P.s.: se vuoi ripristinare la pubblicità, SENZA, dover resettare a impostazioni di fabbrica, basta che cancelli il file nascosto `Kindle/system/.assets` (occhio che il file è nascosto, se usi mac, ma forse anche windows, devi trovare una guida su come mostrare i file nascosti!)
