### ISSUE TITLE
Worked perfectly, thanks a lot!

### ISSUE THREAD

**Issue by lelediaz** [mariopepe/KindleAdRemover#5]
I just wanted to say thank you, this worked just great.
I own a kindle paperwhite 11th generation which I bought in early 2023.
However I have the version with ads and don’t see the point in paying for letting the ads removed. I also asked the support multiple times to remove them for me but they did not, so I guess doing it my own way then. 
searching for this to remove ads on kindle, your repo was the first to pop up so I gave it a shot and now I don’t see any ads anymore.
So once again thanks for this it worked perfectly and made it ad free!!

**Comment by mariopepe** [comment]
Very happy to hear!!! 😃!!!!
